export enum CollectorsMap {
    Asset = 'Asset',
    Log = 'Log',
    Event = 'Event',
    Exception = 'Exception',
    Service = 'Service',
    Timeline = 'Timeline',
    Validator = 'Validator',
    Database = 'Database',
    Queue = 'Queue',
    HttpClient = 'HttpClient',
    FilesystemStream = 'FilesystemStream',
    HttpStream = 'HttpStream',
    ConsoleAppInfo = 'ConsoleAppInfo',
    WebAppInfo = 'WebAppInfo',
    Command = 'Command',
    Middleware = 'Middleware ',
    Request = 'Request',
    Mailer = 'Mailer',
    Router = 'Router',
    VarDumper = 'VarDumper',
    WebView = 'WebView',
}
